// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gifte.Repositories.Models;

public partial class Cart
{
    public int CartId { get; set; }

    public int? UserAccountId { get; set; }

    public int? ProductId { get; set; }

    public int? Quantity { get; set; }

    public DateTime? AddedAt { get; set; }

    public virtual Product Product { get; set; }

    public virtual UserAccount UserAccount { get; set; }
}