// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gifte.Repositories.Models;

public partial class Customization
{
    public int CustomizationId { get; set; }

    public int? OrderDetailId { get; set; }

    public string CustomText { get; set; }

    public string ImageUrl { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }
}